// config/keywords.ts
// ══════════════════════════════════════════════════════════════════════════════
// Google Trends — 1000 seed keywords for Indian creator economy
//
// Tier A (200) — Broad niche seeds. Scraped TWICE daily (fast cycle).
// Tier B (600) — Micro-niche keywords. Scraped ONCE daily (slow cycle).
// Tier C (200) — Breakout watchers + seasonal. Scraped ONCE daily, 
//                deep-dive triggered on spike.
//
// geo: "IN" on all requests — Indian creator platform.
// ══════════════════════════════════════════════════════════════════════════════

import type { KeywordEntry, TrendTier } from "../types/index";

// ── TIER A — Broad seeds (200) ────────────────────────────────────────────────

const TIER_A_KEYWORDS: Omit<KeywordEntry, "tier">[] = [
  // Lifestyle / Vlog (20)
  { keyword: "vlog india",                   niche: "lifestyle" },
  { keyword: "day in my life india",         niche: "lifestyle" },
  { keyword: "indian lifestyle blogger",     niche: "lifestyle" },
  { keyword: "morning routine india",        niche: "lifestyle" },
  { keyword: "aesthetic room india",         niche: "lifestyle" },
  { keyword: "minimalist lifestyle india",   niche: "lifestyle" },
  { keyword: "college life india vlog",      niche: "lifestyle" },
  { keyword: "mumbai vlog",                  niche: "lifestyle" },
  { keyword: "bangalore vlog",               niche: "lifestyle" },
  { keyword: "delhi vlog",                   niche: "lifestyle" },
  { keyword: "solo travel india",            niche: "lifestyle" },
  { keyword: "budget travel india",          niche: "lifestyle" },
  { keyword: "indian wedding vlog",          niche: "lifestyle" },
  { keyword: "house tour india",             niche: "lifestyle" },
  { keyword: "night routine india",          niche: "lifestyle" },
  { keyword: "study with me india",          niche: "lifestyle" },
  { keyword: "productivity india",           niche: "lifestyle" },
  { keyword: "self improvement india",       niche: "lifestyle" },
  { keyword: "get ready with me india",      niche: "lifestyle" },
  { keyword: "daily routine india",          niche: "lifestyle" },

  // Finance / Investing (20)
  { keyword: "stock market india",           niche: "finance" },
  { keyword: "mutual funds india",           niche: "finance" },
  { keyword: "zerodha",                      niche: "finance" },
  { keyword: "sip investment india",         niche: "finance" },
  { keyword: "personal finance india",       niche: "finance" },
  { keyword: "how to invest india",          niche: "finance" },
  { keyword: "nifty 50",                     niche: "finance" },
  { keyword: "share market tips india",      niche: "finance" },
  { keyword: "financial planning india",     niche: "finance" },
  { keyword: "saving money india",           niche: "finance" },
  { keyword: "crypto india",                 niche: "finance" },
  { keyword: "real estate india invest",     niche: "finance" },
  { keyword: "passive income india",         niche: "finance" },
  { keyword: "budget planning india",        niche: "finance" },
  { keyword: "tax saving india",             niche: "finance" },
  { keyword: "fd vs sip",                    niche: "finance" },
  { keyword: "sensex today",                 niche: "finance" },
  { keyword: "smallcase investing",          niche: "finance" },
  { keyword: "groww app",                    niche: "finance" },
  { keyword: "angel one trading",            niche: "finance" },

  // Tech / Gadgets (20)
  { keyword: "best smartphone india 2025",   niche: "tech" },
  { keyword: "iphone india",                 niche: "tech" },
  { keyword: "samsung india 2025",           niche: "tech" },
  { keyword: "ai tools india",              niche: "tech" },
  { keyword: "chatgpt india",               niche: "tech" },
  { keyword: "budget phone india",          niche: "tech" },
  { keyword: "laptop under 50000 india",    niche: "tech" },
  { keyword: "tech news india",             niche: "tech" },
  { keyword: "oneplus india",               niche: "tech" },
  { keyword: "realme vs poco india",        niche: "tech" },
  { keyword: "gaming phone india",          niche: "tech" },
  { keyword: "smartwatch india",            niche: "tech" },
  { keyword: "earbuds india best",          niche: "tech" },
  { keyword: "5g india",                    niche: "tech" },
  { keyword: "software jobs india",         niche: "tech" },
  { keyword: "coding india",               niche: "tech" },
  { keyword: "web development india",       niche: "tech" },
  { keyword: "app development india",       niche: "tech" },
  { keyword: "data science india",          niche: "tech" },
  { keyword: "cybersecurity india",         niche: "tech" },

  // Food / Cooking (20)
  { keyword: "indian food recipes",         niche: "food" },
  { keyword: "street food india",           niche: "food" },
  { keyword: "mumbai street food",          niche: "food" },
  { keyword: "quick recipes india",         niche: "food" },
  { keyword: "biryani recipe",              niche: "food" },
  { keyword: "healthy food india",          niche: "food" },
  { keyword: "food vlog india",             niche: "food" },
  { keyword: "restaurant review india",     niche: "food" },
  { keyword: "zomato food",                niche: "food" },
  { keyword: "swiggy india",               niche: "food" },
  { keyword: "baking india",               niche: "food" },
  { keyword: "dal chawal recipe",           niche: "food" },
  { keyword: "south indian food",           niche: "food" },
  { keyword: "north indian recipes",        niche: "food" },
  { keyword: "weight loss diet india",      niche: "food" },
  { keyword: "protein diet india",          niche: "food" },
  { keyword: "keto india",                  niche: "food" },
  { keyword: "vegan india food",            niche: "food" },
  { keyword: "cafe india",                  niche: "food" },
  { keyword: "chai recipes india",          niche: "food" },

  // Fashion / Beauty (20)
  { keyword: "indian fashion 2025",         niche: "fashion" },
  { keyword: "saree styling",               niche: "fashion" },
  { keyword: "kurta set women india",       niche: "fashion" },
  { keyword: "skincare routine india",      niche: "fashion" },
  { keyword: "makeup tutorial india",       niche: "fashion" },
  { keyword: "myntra haul",                 niche: "fashion" },
  { keyword: "nykaa beauty india",          niche: "fashion" },
  { keyword: "haircare routine india",      niche: "fashion" },
  { keyword: "ethnic wear india",           niche: "fashion" },
  { keyword: "outfit of the day india",     niche: "fashion" },
  { keyword: "budget fashion india",        niche: "fashion" },
  { keyword: "thrift shopping india",       niche: "fashion" },
  { keyword: "mens fashion india",          niche: "fashion" },
  { keyword: "streetwear india",            niche: "fashion" },
  { keyword: "korean skincare india",       niche: "fashion" },
  { keyword: "natural hair india",          niche: "fashion" },
  { keyword: "meesho fashion haul",         niche: "fashion" },
  { keyword: "amazon fashion india",        niche: "fashion" },
  { keyword: "nail art india",              niche: "fashion" },
  { keyword: "bridal makeup india",         niche: "fashion" },

  // Gaming (20)
  { keyword: "bgmi india",                  niche: "gaming" },
  { keyword: "free fire india",             niche: "gaming" },
  { keyword: "valorant india",              niche: "gaming" },
  { keyword: "minecraft india",             niche: "gaming" },
  { keyword: "gaming setup india",          niche: "gaming" },
  { keyword: "mobile gaming india",         niche: "gaming" },
  { keyword: "pc gaming india",             niche: "gaming" },
  { keyword: "gta india",                   niche: "gaming" },
  { keyword: "esports india",               niche: "gaming" },
  { keyword: "gaming youtuber india",       niche: "gaming" },
  { keyword: "cod mobile india",            niche: "gaming" },
  { keyword: "among us india",              niche: "gaming" },
  { keyword: "roblox india",               niche: "gaming" },
  { keyword: "gaming chair india",          niche: "gaming" },
  { keyword: "fps games india",             niche: "gaming" },
  { keyword: "streaming setup india",       niche: "gaming" },
  { keyword: "youtube gaming india",        niche: "gaming" },
  { keyword: "twitch india",               niche: "gaming" },
  { keyword: "gaming headset india",        niche: "gaming" },
  { keyword: "game review india",           niche: "gaming" },

  // Fitness / Health (20)
  { keyword: "gym workout india",           niche: "fitness" },
  { keyword: "home workout india",          niche: "fitness" },
  { keyword: "yoga india",                  niche: "fitness" },
  { keyword: "weight loss india",           niche: "fitness" },
  { keyword: "muscle building india",       niche: "fitness" },
  { keyword: "fitness india",              niche: "fitness" },
  { keyword: "calisthenics india",          niche: "fitness" },
  { keyword: "diet plan india",             niche: "fitness" },
  { keyword: "protein supplement india",    niche: "fitness" },
  { keyword: "running india",              niche: "fitness" },
  { keyword: "mental health india",         niche: "fitness" },
  { keyword: "meditation india",            niche: "fitness" },
  { keyword: "ayurveda india",              niche: "fitness" },
  { keyword: "zumba india",                niche: "fitness" },
  { keyword: "crossfit india",             niche: "fitness" },
  { keyword: "gym motivation india",        niche: "fitness" },
  { keyword: "abs workout india",           niche: "fitness" },
  { keyword: "sports nutrition india",      niche: "fitness" },
  { keyword: "pilates india",              niche: "fitness" },
  { keyword: "wellness india",             niche: "fitness" },

  // Education / Career (20)
  { keyword: "upsc preparation",            niche: "education" },
  { keyword: "jee preparation",             niche: "education" },
  { keyword: "neet preparation",            niche: "education" },
  { keyword: "study tips india",            niche: "education" },
  { keyword: "government jobs india",       niche: "education" },
  { keyword: "freelancing india",           niche: "education" },
  { keyword: "online earning india",        niche: "education" },
  { keyword: "mba india",                  niche: "education" },
  { keyword: "cat exam india",              niche: "education" },
  { keyword: "ielts india",                niche: "education" },
  { keyword: "study abroad india",          niche: "education" },
  { keyword: "engineering india",           niche: "education" },
  { keyword: "digital marketing india",     niche: "education" },
  { keyword: "content creator career",      niche: "education" },
  { keyword: "youtube career india",        niche: "education" },
  { keyword: "instagram monetization",      niche: "education" },
  { keyword: "startup india",              niche: "education" },
  { keyword: "entrepreneur india",          niche: "education" },
  { keyword: "side hustle india",           niche: "education" },
  { keyword: "work from home india",        niche: "education" },

  // Entertainment / Bollywood (20)
  { keyword: "bollywood 2025",              niche: "entertainment" },
  { keyword: "new hindi movies 2025",       niche: "entertainment" },
  { keyword: "ipl 2025",                   niche: "entertainment" },
  { keyword: "cricket india",              niche: "entertainment" },
  { keyword: "netflix india",              niche: "entertainment" },
  { keyword: "amazon prime india",          niche: "entertainment" },
  { keyword: "web series india 2025",       niche: "entertainment" },
  { keyword: "bollywood songs 2025",        niche: "entertainment" },
  { keyword: "rohit sharma",              niche: "entertainment" },
  { keyword: "virat kohli",               niche: "entertainment" },
  { keyword: "standup comedy india",        niche: "entertainment" },
  { keyword: "karan johar",               niche: "entertainment" },
  { keyword: "desi memes",                niche: "entertainment" },
  { keyword: "punjabi songs 2025",          niche: "entertainment" },
  { keyword: "new south movie india",       niche: "entertainment" },
  { keyword: "disney plus hotstar",         niche: "entertainment" },
  { keyword: "reality show india 2025",     niche: "entertainment" },
  { keyword: "bigg boss 2025",             niche: "entertainment" },
  { keyword: "bts india fans",             niche: "entertainment" },
  { keyword: "k drama india",             niche: "entertainment" },

  // Creator / Social Media (20)
  { keyword: "instagram reels ideas",       niche: "creator" },
  { keyword: "youtube shorts india",        niche: "creator" },
  { keyword: "content creator india",       niche: "creator" },
  { keyword: "how to grow instagram india", niche: "creator" },
  { keyword: "viral reels india",           niche: "creator" },
  { keyword: "trending audio instagram",    niche: "creator" },
  { keyword: "youtube monetization india",  niche: "creator" },
  { keyword: "reel ideas hindi",            niche: "creator" },
  { keyword: "faceless youtube india",      niche: "creator" },
  { keyword: "podcast india",             niche: "creator" },
  { keyword: "influencer marketing india",  niche: "creator" },
  { keyword: "brand deals india",          niche: "creator" },
  { keyword: "editing tips reels",          niche: "creator" },
  { keyword: "caption ideas instagram",     niche: "creator" },
  { keyword: "hashtags india instagram",    niche: "creator" },
  { keyword: "thumbnail ideas youtube",     niche: "creator" },
  { keyword: "hook ideas reels",            niche: "creator" },
  { keyword: "viral content india",         niche: "creator" },
  { keyword: "instagram algorithm india",   niche: "creator" },
  { keyword: "youtube algorithm india",     niche: "creator" },
];

// ── TIER B — Micro-niche keywords (600) ──────────────────────────────────────

const TIER_B_KEYWORDS: Omit<KeywordEntry, "tier">[] = [
  // Lifestyle (60)
  { keyword: "capsule wardrobe india",         niche: "lifestyle" },
  { keyword: "minimalist home decor india",    niche: "lifestyle" },
  { keyword: "apartment tour india 2025",      niche: "lifestyle" },
  { keyword: "journaling india",               niche: "lifestyle" },
  { keyword: "reading routine india",          niche: "lifestyle" },
  { keyword: "book recommendations india",     niche: "lifestyle" },
  { keyword: "slow living india",              niche: "lifestyle" },
  { keyword: "digital detox india",            niche: "lifestyle" },
  { keyword: "sunday routine india",           niche: "lifestyle" },
  { keyword: "college hostel life india",      niche: "lifestyle" },
  { keyword: "pg life india vlog",             niche: "lifestyle" },
  { keyword: "hyderabad vlog",                 niche: "lifestyle" },
  { keyword: "pune vlog",                      niche: "lifestyle" },
  { keyword: "chennai vlog",                   niche: "lifestyle" },
  { keyword: "kolkata vlog",                   niche: "lifestyle" },
  { keyword: "ahmedabad vlog",                 niche: "lifestyle" },
  { keyword: "international travel indian",    niche: "lifestyle" },
  { keyword: "visa process india",             niche: "lifestyle" },
  { keyword: "europe trip from india",         niche: "lifestyle" },
  { keyword: "bali from india trip",           niche: "lifestyle" },
  { keyword: "thailand trip india budget",     niche: "lifestyle" },
  { keyword: "goa trip 2025",                  niche: "lifestyle" },
  { keyword: "himachal trip india",            niche: "lifestyle" },
  { keyword: "kerala trip india",              niche: "lifestyle" },
  { keyword: "rajasthan trip india",           niche: "lifestyle" },
  { keyword: "corporate life india vlog",      niche: "lifestyle" },
  { keyword: "work life balance india",        niche: "lifestyle" },
  { keyword: "remote work india",              niche: "lifestyle" },
  { keyword: "coworking space india",          niche: "lifestyle" },
  { keyword: "renting house india tips",       niche: "lifestyle" },
  { keyword: "living alone india",             niche: "lifestyle" },
  { keyword: "flatmate india experience",      niche: "lifestyle" },
  { keyword: "moving city india experience",   niche: "lifestyle" },
  { keyword: "24 hours india challenge",       niche: "lifestyle" },
  { keyword: "birthday celebration india",     niche: "lifestyle" },
  { keyword: "relationship advice india",      niche: "lifestyle" },
  { keyword: "dating india tips",              niche: "lifestyle" },
  { keyword: "mental peace india",             niche: "lifestyle" },
  { keyword: "anxiety india youth",            niche: "lifestyle" },
  { keyword: "introverted life india",         niche: "lifestyle" },
  { keyword: "night market india",             niche: "lifestyle" },
  { keyword: "sunday market india",            niche: "lifestyle" },
  { keyword: "stationery haul india",          niche: "lifestyle" },
  { keyword: "amazon haul india",              niche: "lifestyle" },
  { keyword: "flipkart haul india",            niche: "lifestyle" },
  { keyword: "grocery haul india",             niche: "lifestyle" },
  { keyword: "plant collection india",         niche: "lifestyle" },
  { keyword: "pet care india",                 niche: "lifestyle" },
  { keyword: "dog vlog india",                 niche: "lifestyle" },
  { keyword: "cat vlog india",                 niche: "lifestyle" },
  { keyword: "zero waste india",              niche: "lifestyle" },
  { keyword: "sustainable living india",       niche: "lifestyle" },
  { keyword: "ev car india experience",        niche: "lifestyle" },
  { keyword: "car vlog india",                 niche: "lifestyle" },
  { keyword: "bike trip india",                niche: "lifestyle" },
  { keyword: "road trip india 2025",           niche: "lifestyle" },
  { keyword: "camping india",                  niche: "lifestyle" },
  { keyword: "trekking india beginner",        niche: "lifestyle" },
  { keyword: "hostel review india",            niche: "lifestyle" },
  { keyword: "airbnb india experience",        niche: "lifestyle" },

  // Finance (60)
  { keyword: "zerodha vs groww comparison",    niche: "finance" },
  { keyword: "index funds india beginners",    niche: "finance" },
  { keyword: "nifty 50 etf india",            niche: "finance" },
  { keyword: "small cap funds india",          niche: "finance" },
  { keyword: "large cap funds india",          niche: "finance" },
  { keyword: "flexi cap fund india",           niche: "finance" },
  { keyword: "elss tax saving funds",          niche: "finance" },
  { keyword: "ppf vs nps india",              niche: "finance" },
  { keyword: "epf withdrawal india",           niche: "finance" },
  { keyword: "income tax india 2025",          niche: "finance" },
  { keyword: "itr filing india how to",        niche: "finance" },
  { keyword: "gst india small business",       niche: "finance" },
  { keyword: "f&o trading india beginners",    niche: "finance" },
  { keyword: "swing trading india",            niche: "finance" },
  { keyword: "intraday trading india tips",    niche: "finance" },
  { keyword: "technical analysis india",       niche: "finance" },
  { keyword: "stock screener india",           niche: "finance" },
  { keyword: "ipo india 2025",                niche: "finance" },
  { keyword: "grey market premium india",      niche: "finance" },
  { keyword: "real estate vs stocks india",    niche: "finance" },
  { keyword: "gold investment india 2025",     niche: "finance" },
  { keyword: "sovereign gold bond india",      niche: "finance" },
  { keyword: "rbi policy india",               niche: "finance" },
  { keyword: "inflation india 2025",           niche: "finance" },
  { keyword: "recession india 2025",           niche: "finance" },
  { keyword: "dollar vs rupee",               niche: "finance" },
  { keyword: "international mutual funds",     niche: "finance" },
  { keyword: "us stocks from india",           niche: "finance" },
  { keyword: "web3 india investment",          niche: "finance" },
  { keyword: "bitcoin india 2025",             niche: "finance" },
  { keyword: "defi india",                    niche: "finance" },
  { keyword: "credit score india improve",     niche: "finance" },
  { keyword: "credit card india best",         niche: "finance" },
  { keyword: "credit card cashback india",     niche: "finance" },
  { keyword: "hdfc credit card review",        niche: "finance" },
  { keyword: "sbi credit card review",         niche: "finance" },
  { keyword: "loan india tips",               niche: "finance" },
  { keyword: "home loan india 2025",           niche: "finance" },
  { keyword: "education loan india",           niche: "finance" },
  { keyword: "salary negotiation india",       niche: "finance" },
  { keyword: "salary hike india 2025",         niche: "finance" },
  { keyword: "salary slip india",             niche: "finance" },
  { keyword: "pf deduction india",            niche: "finance" },
  { keyword: "emergency fund india",           niche: "finance" },
  { keyword: "financial freedom india age 30", niche: "finance" },
  { keyword: "fire movement india",            niche: "finance" },
  { keyword: "1 crore retirement india",       niche: "finance" },
  { keyword: "compound interest india",        niche: "finance" },
  { keyword: "dividend stocks india",          niche: "finance" },
  { keyword: "multi cap fund india",           niche: "finance" },
  { keyword: "thematic funds india",           niche: "finance" },
  { keyword: "sectoral fund india",            niche: "finance" },
  { keyword: "stock market crash india",       niche: "finance" },
  { keyword: "market correction india",        niche: "finance" },
  { keyword: "bear market india strategy",     niche: "finance" },
  { keyword: "portfolio review india",         niche: "finance" },
  { keyword: "rebalancing portfolio india",    niche: "finance" },
  { keyword: "insurance india term plan",      niche: "finance" },
  { keyword: "health insurance india 2025",    niche: "finance" },
  { keyword: "will making india",              niche: "finance" },

  // Tech (60)
  { keyword: "pixel 9 india review",          niche: "tech" },
  { keyword: "iphone 17 india",               niche: "tech" },
  { keyword: "samsung s25 india review",       niche: "tech" },
  { keyword: "redmi note india 2025",          niche: "tech" },
  { keyword: "poco x series india",           niche: "tech" },
  { keyword: "nothing phone india",           niche: "tech" },
  { keyword: "iqoo india review",             niche: "tech" },
  { keyword: "vivo india phone 2025",          niche: "tech" },
  { keyword: "oppo india 2025",               niche: "tech" },
  { keyword: "micromax india 2025",           niche: "tech" },
  { keyword: "macbook air india review",       niche: "tech" },
  { keyword: "dell vs hp laptop india",        niche: "tech" },
  { keyword: "asus gaming laptop india",       niche: "tech" },
  { keyword: "chromebook india",              niche: "tech" },
  { keyword: "ipad india review",             niche: "tech" },
  { keyword: "tablet india best 2025",        niche: "tech" },
  { keyword: "kindle india review",           niche: "tech" },
  { keyword: "boAt earbuds india",            niche: "tech" },
  { keyword: "jbl speaker india",             niche: "tech" },
  { keyword: "sony headphones india",         niche: "tech" },
  { keyword: "wifi router india best",        niche: "tech" },
  { keyword: "smart tv india 2025",           niche: "tech" },
  { keyword: "mi tv india review",            niche: "tech" },
  { keyword: "ac india energy saving",        niche: "tech" },
  { keyword: "solar panel india home",        niche: "tech" },
  { keyword: "ev charging india",             niche: "tech" },
  { keyword: "ola electric india review",     niche: "tech" },
  { keyword: "gemini ai india",               niche: "tech" },
  { keyword: "claude ai india",               niche: "tech" },
  { keyword: "perplexity ai india",           niche: "tech" },
  { keyword: "ai video generator india",      niche: "tech" },
  { keyword: "midjourney india tutorial",     niche: "tech" },
  { keyword: "canva pro india",               niche: "tech" },
  { keyword: "notion india template",         niche: "tech" },
  { keyword: "obsidian notes india",          niche: "tech" },
  { keyword: "python india tutorial",         niche: "tech" },
  { keyword: "javascript india course",       niche: "tech" },
  { keyword: "react native india",            niche: "tech" },
  { keyword: "flutter india course",          niche: "tech" },
  { keyword: "devops india jobs",             niche: "tech" },
  { keyword: "cloud computing india jobs",    niche: "tech" },
  { keyword: "aws india certification",       niche: "tech" },
  { keyword: "machine learning india",        niche: "tech" },
  { keyword: "prompt engineering india",      niche: "tech" },
  { keyword: "blockchain india jobs",         niche: "tech" },
  { keyword: "hackathon india 2025",          niche: "tech" },
  { keyword: "startup funding india tech",    niche: "tech" },
  { keyword: "product manager india",        niche: "tech" },
  { keyword: "ux design india career",        niche: "tech" },
  { keyword: "freelance developer india",     niche: "tech" },
  { keyword: "topmate india",                 niche: "tech" },
  { keyword: "internshala india review",      niche: "tech" },
  { keyword: "linkedin india profile tips",   niche: "tech" },
  { keyword: "github india",                  niche: "tech" },
  { keyword: "open source india",             niche: "tech" },
  { keyword: "chat gpt alternatives india",   niche: "tech" },
  { keyword: "ai image india",                niche: "tech" },
  { keyword: "tech unboxing india",           niche: "tech" },
  { keyword: "buy refurbished phone india",   niche: "tech" },
  { keyword: "second hand laptop india",      niche: "tech" },

  // Food (60)
  { keyword: "paneer recipes india",          niche: "food" },
  { keyword: "dal tadka recipe",              niche: "food" },
  { keyword: "rajma chawal recipe",           niche: "food" },
  { keyword: "chole bhature recipe",          niche: "food" },
  { keyword: "pav bhaji recipe",              niche: "food" },
  { keyword: "dosa recipe",                  niche: "food" },
  { keyword: "idli sambar recipe",            niche: "food" },
  { keyword: "aloo paratha recipe",           niche: "food" },
  { keyword: "momos recipe india",            niche: "food" },
  { keyword: "pasta indian style recipe",     niche: "food" },
  { keyword: "noodles india recipe",          niche: "food" },
  { keyword: "sandwich recipe india",         niche: "food" },
  { keyword: "healthy breakfast india",       niche: "food" },
  { keyword: "protein breakfast india",       niche: "food" },
  { keyword: "smoothie recipe india",         niche: "food" },
  { keyword: "detox drinks india",            niche: "food" },
  { keyword: "immune boosting food india",    niche: "food" },
  { keyword: "weight loss recipe india",      niche: "food" },
  { keyword: "gym diet plan india",           niche: "food" },
  { keyword: "intermittent fasting india",    niche: "food" },
  { keyword: "ramadan food india",            niche: "food" },
  { keyword: "navratri fasting food",         niche: "food" },
  { keyword: "diwali sweets recipe",          niche: "food" },
  { keyword: "holi recipes india",            niche: "food" },
  { keyword: "monsoon snacks india",          niche: "food" },
  { keyword: "winter recipes india",          niche: "food" },
  { keyword: "summer drinks india",           niche: "food" },
  { keyword: "kolkata street food",           niche: "food" },
  { keyword: "delhi street food",             niche: "food" },
  { keyword: "pune cafe list",                niche: "food" },
  { keyword: "bangalore food blog",           niche: "food" },
  { keyword: "hyderabad food vlog",           niche: "food" },
  { keyword: "ahmedabad street food",         niche: "food" },
  { keyword: "jaipur food trip",              niche: "food" },
  { keyword: "amritsar food vlog",            niche: "food" },
  { keyword: "varanasi food tour",            niche: "food" },
  { keyword: "goa seafood vlog",              niche: "food" },
  { keyword: "mangalore food vlog",           niche: "food" },
  { keyword: "lucknow biryani review",        niche: "food" },
  { keyword: "haleem recipe india",           niche: "food" },
  { keyword: "butter chicken recipe",         niche: "food" },
  { keyword: "tikka masala recipe india",     niche: "food" },
  { keyword: "gulab jamun recipe",            niche: "food" },
  { keyword: "rasgulla recipe",               niche: "food" },
  { keyword: "kheer recipe india",            niche: "food" },
  { keyword: "kulfi recipe india",            niche: "food" },
  { keyword: "jalebi recipe india",           niche: "food" },
  { keyword: "ragi recipes india",            niche: "food" },
  { keyword: "millets india recipes",         niche: "food" },
  { keyword: "air fryer recipes india",       niche: "food" },
  { keyword: "microwave recipes india",       niche: "food" },
  { keyword: "pressure cooker india recipes", niche: "food" },
  { keyword: "instant pot india recipes",     niche: "food" },
  { keyword: "one pot meal india",            niche: "food" },
  { keyword: "5 minute recipes india",        niche: "food" },
  { keyword: "college food india cheap",      niche: "food" },
  { keyword: "hostel cooking india",          niche: "food" },
  { keyword: "meal prep india",               niche: "food" },
  { keyword: "tiffin recipe india",           niche: "food" },
  { keyword: "lunch box india kids",          niche: "food" },

  // Fashion (60)
  { keyword: "indo western outfits india",    niche: "fashion" },
  { keyword: "lehenga styling ideas",         niche: "fashion" },
  { keyword: "anarkali suit styling",         niche: "fashion" },
  { keyword: "palazzo pants india outfit",    niche: "fashion" },
  { keyword: "co ord set india trend",        niche: "fashion" },
  { keyword: "denim jacket styling india",    niche: "fashion" },
  { keyword: "oversized tshirt outfit india", niche: "fashion" },
  { keyword: "blazer outfit women india",     niche: "fashion" },
  { keyword: "office wear india women",       niche: "fashion" },
  { keyword: "college outfit ideas girls",    niche: "fashion" },
  { keyword: "party outfit india women",      niche: "fashion" },
  { keyword: "casual outfit india men",       niche: "fashion" },
  { keyword: "wedding guest outfit india",    niche: "fashion" },
  { keyword: "summer outfit india 2025",      niche: "fashion" },
  { keyword: "winter fashion india 2025",     niche: "fashion" },
  { keyword: "monsoon outfit india",          niche: "fashion" },
  { keyword: "sustainable fashion india",     niche: "fashion" },
  { keyword: "second hand clothing india",    niche: "fashion" },
  { keyword: "relove india fashion",          niche: "fashion" },
  { keyword: "shein india alternatives",      niche: "fashion" },
  { keyword: "zara india dupes",              niche: "fashion" },
  { keyword: "h&m india review",             niche: "fashion" },
  { keyword: "uniqlo india review",           niche: "fashion" },
  { keyword: "biba fashion india",            niche: "fashion" },
  { keyword: "w for woman india",             niche: "fashion" },
  { keyword: "glass skin routine india",      niche: "fashion" },
  { keyword: "double cleansing india",        niche: "fashion" },
  { keyword: "sunscreen india best",          niche: "fashion" },
  { keyword: "vitamin c serum india",         niche: "fashion" },
  { keyword: "retinol india skincare",        niche: "fashion" },
  { keyword: "hyaluronic acid india",         niche: "fashion" },
  { keyword: "ayurvedic skincare india",      niche: "fashion" },
  { keyword: "multani mitti face pack",       niche: "fashion" },
  { keyword: "besan face pack india",         niche: "fashion" },
  { keyword: "rice water skincare india",     niche: "fashion" },
  { keyword: "oily skin routine india",       niche: "fashion" },
  { keyword: "dry skin routine india",        niche: "fashion" },
  { keyword: "acne treatment india",          niche: "fashion" },
  { keyword: "dark circles india remedy",     niche: "fashion" },
  { keyword: "lip care routine india",        niche: "fashion" },
  { keyword: "eyebrow shaping india",         niche: "fashion" },
  { keyword: "eyeliner tutorial india",       niche: "fashion" },
  { keyword: "foundation india dusky skin",   niche: "fashion" },
  { keyword: "kajal india best",              niche: "fashion" },
  { keyword: "lipstick shades india",         niche: "fashion" },
  { keyword: "hair oiling routine india",     niche: "fashion" },
  { keyword: "hair mask india diy",           niche: "fashion" },
  { keyword: "onion oil india review",        niche: "fashion" },
  { keyword: "hair fall remedy india",        niche: "fashion" },
  { keyword: "scalp care india",              niche: "fashion" },
  { keyword: "henna hair india",              niche: "fashion" },
  { keyword: "hair color india trend 2025",   niche: "fashion" },
  { keyword: "balayage india cost",           niche: "fashion" },
  { keyword: "keratin treatment india",       niche: "fashion" },
  { keyword: "waxing at home india",          niche: "fashion" },
  { keyword: "threading eyebrow india",       niche: "fashion" },
  { keyword: "perfume india best",            niche: "fashion" },
  { keyword: "jewellery india online",        niche: "fashion" },
  { keyword: "artificial jewellery india",    niche: "fashion" },
  { keyword: "handbag india affordable",      niche: "fashion" },

  // Gaming (60)
  { keyword: "bgmi rank push tips",           niche: "gaming" },
  { keyword: "bgmi best gun 2025",            niche: "gaming" },
  { keyword: "free fire max india tips",      niche: "gaming" },
  { keyword: "valorant agent tier list",      niche: "gaming" },
  { keyword: "valorant rank india",           niche: "gaming" },
  { keyword: "minecraft survival tips india", niche: "gaming" },
  { keyword: "minecraft house ideas india",   niche: "gaming" },
  { keyword: "gta 6 india release date",     niche: "gaming" },
  { keyword: "gta 5 mods india",             niche: "gaming" },
  { keyword: "cod warzone india settings",    niche: "gaming" },
  { keyword: "apex legends india",            niche: "gaming" },
  { keyword: "pubg pc india 2025",            niche: "gaming" },
  { keyword: "pokemon go india events",       niche: "gaming" },
  { keyword: "clash of clans india tips",     niche: "gaming" },
  { keyword: "clash royale india",            niche: "gaming" },
  { keyword: "mobile legends india",          niche: "gaming" },
  { keyword: "chess india online",            niche: "gaming" },
  { keyword: "ludo king india tips",          niche: "gaming" },
  { keyword: "rummy india online",            niche: "gaming" },
  { keyword: "fantasy cricket india tips",    niche: "gaming" },
  { keyword: "dream11 tips india",            niche: "gaming" },
  { keyword: "myteam11 india review",         niche: "gaming" },
  { keyword: "gaming keyboard india",         niche: "gaming" },
  { keyword: "gaming mouse india budget",     niche: "gaming" },
  { keyword: "gaming monitor india",          niche: "gaming" },
  { keyword: "capture card india",            niche: "gaming" },
  { keyword: "obs setup india tutorial",      niche: "gaming" },
  { keyword: "streamlabs india",              niche: "gaming" },
  { keyword: "how to stream india",           niche: "gaming" },
  { keyword: "youtube gaming channel india",  niche: "gaming" },
  { keyword: "gaming sponsor india",          niche: "gaming" },
  { keyword: "esports career india",          niche: "gaming" },
  { keyword: "bgmi esports india",            niche: "gaming" },
  { keyword: "esports team india join",       niche: "gaming" },
  { keyword: "gaming scholarship india",      niche: "gaming" },
  { keyword: "gaming tournament india",       niche: "gaming" },
  { keyword: "rog phone india review",        niche: "gaming" },
  { keyword: "asus rog india",                niche: "gaming" },
  { keyword: "ps5 india price",               niche: "gaming" },
  { keyword: "xbox india review",             niche: "gaming" },
  { keyword: "nintendo switch india",         niche: "gaming" },
  { keyword: "retro gaming india",            niche: "gaming" },
  { keyword: "best indie games india",        niche: "gaming" },
  { keyword: "horror games india",            niche: "gaming" },
  { keyword: "open world games india",        niche: "gaming" },
  { keyword: "rpg games india mobile",        niche: "gaming" },
  { keyword: "strategy games india",          niche: "gaming" },
  { keyword: "racing games india mobile",     niche: "gaming" },
  { keyword: "vr gaming india",               niche: "gaming" },
  { keyword: "gaming addiction india",        niche: "gaming" },
  { keyword: "gaming income india",           niche: "gaming" },
  { keyword: "youtube gaming monetize india", niche: "gaming" },
  { keyword: "gaming merchandise india",      niche: "gaming" },
  { keyword: "gaming cafes india",            niche: "gaming" },
  { keyword: "gaming zone india",             niche: "gaming" },
  { keyword: "gaming influencer india",       niche: "gaming" },
  { keyword: "carryminati new video",         niche: "gaming" },
  { keyword: "mortal gaming india",           niche: "gaming" },
  { keyword: "dynamo gaming india",           niche: "gaming" },
  { keyword: "kronten gaming india",          niche: "gaming" },

  // Fitness (60)
  { keyword: "chest workout india home",      niche: "fitness" },
  { keyword: "back workout india gym",        niche: "fitness" },
  { keyword: "leg day workout india",         niche: "fitness" },
  { keyword: "shoulder workout india",        niche: "fitness" },
  { keyword: "bicep workout india tips",      niche: "fitness" },
  { keyword: "tricep workout india",          niche: "fitness" },
  { keyword: "pull up india tips",            niche: "fitness" },
  { keyword: "push up variations india",      niche: "fitness" },
  { keyword: "plank workout india",           niche: "fitness" },
  { keyword: "hiit workout india",            niche: "fitness" },
  { keyword: "tabata india workout",          niche: "fitness" },
  { keyword: "jump rope india workout",       niche: "fitness" },
  { keyword: "bodyweight workout india",      niche: "fitness" },
  { keyword: "no equipment workout india",    niche: "fitness" },
  { keyword: "beginner gym india guide",      niche: "fitness" },
  { keyword: "gym mistakes india",            niche: "fitness" },
  { keyword: "gym routine india male",        niche: "fitness" },
  { keyword: "gym routine india female",      niche: "fitness" },
  { keyword: "fat loss india workout",        niche: "fitness" },
  { keyword: "belly fat loss india",          niche: "fitness" },
  { keyword: "6 pack abs india",              niche: "fitness" },
  { keyword: "bulking diet india",            niche: "fitness" },
  { keyword: "cutting diet india",            niche: "fitness" },
  { keyword: "creatine india review",         niche: "fitness" },
  { keyword: "whey protein india best",       niche: "fitness" },
  { keyword: "pre workout india review",      niche: "fitness" },
  { keyword: "bcaa india review",             niche: "fitness" },
  { keyword: "mass gainer india",             niche: "fitness" },
  { keyword: "multivitamin india men",        niche: "fitness" },
  { keyword: "vitamin d india supplement",    niche: "fitness" },
  { keyword: "sleep improvement india",       niche: "fitness" },
  { keyword: "yoga morning india routine",    niche: "fitness" },
  { keyword: "pranayama india benefits",      niche: "fitness" },
  { keyword: "surya namaskar india",          niche: "fitness" },
  { keyword: "flexibility india workout",     niche: "fitness" },
  { keyword: "injury recovery india tips",    niche: "fitness" },
  { keyword: "knee pain india exercise",      niche: "fitness" },
  { keyword: "back pain india remedy",        niche: "fitness" },
  { keyword: "posture correction india",      niche: "fitness" },
  { keyword: "running tips india beginner",   niche: "fitness" },
  { keyword: "half marathon india training",  niche: "fitness" },
  { keyword: "marathon india training",       niche: "fitness" },
  { keyword: "cycling india fitness",         niche: "fitness" },
  { keyword: "swimming india fitness",        niche: "fitness" },
  { keyword: "badminton fitness india",       niche: "fitness" },
  { keyword: "cricket fitness india",         niche: "fitness" },
  { keyword: "sports physiotherapy india",    niche: "fitness" },
  { keyword: "pcos fitness india",            niche: "fitness" },
  { keyword: "thyroid fitness india",         niche: "fitness" },
  { keyword: "diabetes fitness india",        niche: "fitness" },
  { keyword: "gut health india tips",         niche: "fitness" },
  { keyword: "probiotic india food",          niche: "fitness" },
  { keyword: "detox week india plan",         niche: "fitness" },
  { keyword: "cold shower india benefits",    niche: "fitness" },
  { keyword: "fasting india health",          niche: "fitness" },
  { keyword: "hormone health india women",    niche: "fitness" },
  { keyword: "testosterone india foods",      niche: "fitness" },
  { keyword: "cortisol india stress",         niche: "fitness" },
  { keyword: "burnout india recovery",        niche: "fitness" },
  { keyword: "sports psychology india",       niche: "fitness" },

  // Education / Career (60)
  { keyword: "upsc syllabus 2025",            niche: "education" },
  { keyword: "upsc daily schedule",           niche: "education" },
  { keyword: "upsc optional subjects",        niche: "education" },
  { keyword: "jee mains preparation tips",    niche: "education" },
  { keyword: "jee advanced india strategy",   niche: "education" },
  { keyword: "neet biology tips india",       niche: "education" },
  { keyword: "gate exam india preparation",   niche: "education" },
  { keyword: "ssc cgl india preparation",     niche: "education" },
  { keyword: "banking exam india tips",       niche: "education" },
  { keyword: "ibps india preparation",        niche: "education" },
  { keyword: "state psc india tips",          niche: "education" },
  { keyword: "defence exam india",            niche: "education" },
  { keyword: "nda exam india",                niche: "education" },
  { keyword: "clat india preparation",        niche: "education" },
  { keyword: "ca course india",               niche: "education" },
  { keyword: "cs exam india",                 niche: "education" },
  { keyword: "cfa india",                     niche: "education" },
  { keyword: "mba abroad india student",      niche: "education" },
  { keyword: "gre india preparation",         niche: "education" },
  { keyword: "gmat india tips",               niche: "education" },
  { keyword: "toefl india preparation",       niche: "education" },
  { keyword: "scholarship india abroad",      niche: "education" },
  { keyword: "resume tips india freshers",    niche: "education" },
  { keyword: "interview tips india",          niche: "education" },
  { keyword: "hr interview india",            niche: "education" },
  { keyword: "technical interview india",     niche: "education" },
  { keyword: "campus placement india tips",   niche: "education" },
  { keyword: "off campus jobs india",         niche: "education" },
  { keyword: "linkedin india job tips",       niche: "education" },
  { keyword: "naukri india tips",             niche: "education" },
  { keyword: "internship india how to get",   niche: "education" },
  { keyword: "unpaid internship india worth", niche: "education" },
  { keyword: "first job india tips",          niche: "education" },
  { keyword: "switching jobs india tips",     niche: "education" },
  { keyword: "layoff india how to handle",    niche: "education" },
  { keyword: "notice period india tips",      niche: "education" },
  { keyword: "appraisal india tips",          niche: "education" },
  { keyword: "promotion india tips",          niche: "education" },
  { keyword: "tcs infosys wipro india",       niche: "education" },
  { keyword: "product based company india",   niche: "education" },
  { keyword: "service based india career",    niche: "education" },
  { keyword: "mnc vs startup india",          niche: "education" },
  { keyword: "wfh india jobs 2025",           niche: "education" },
  { keyword: "fiverr india tips",             niche: "education" },
  { keyword: "upwork india guide",            niche: "education" },
  { keyword: "freelance writing india",       niche: "education" },
  { keyword: "graphic design india career",   niche: "education" },
  { keyword: "video editing india career",    niche: "education" },
  { keyword: "social media manager india",    niche: "education" },
  { keyword: "copywriting india earn",        niche: "education" },
  { keyword: "dropshipping india guide",      niche: "education" },
  { keyword: "ecommerce india tips",          niche: "education" },
  { keyword: "amazon seller india guide",     niche: "education" },
  { keyword: "meesho seller india guide",     niche: "education" },
  { keyword: "affiliate marketing india",     niche: "education" },
  { keyword: "blogging india income",         niche: "education" },
  { keyword: "adsense india tips",            niche: "education" },
  { keyword: "brand collaboration india",     niche: "education" },
  { keyword: "email marketing india",         niche: "education" },
  { keyword: "seo india course",              niche: "education" },

  // Entertainment (60)
  { keyword: "bollywood box office 2025",     niche: "entertainment" },
  { keyword: "ott releases india 2025",       niche: "entertainment" },
  { keyword: "best web series india 2025",    niche: "entertainment" },
  { keyword: "netflix india series review",   niche: "entertainment" },
  { keyword: "amazon prime india series",     niche: "entertainment" },
  { keyword: "zee5 india series review",      niche: "entertainment" },
  { keyword: "sonyliv india series 2025",     niche: "entertainment" },
  { keyword: "mirzapur season 3",             niche: "entertainment" },
  { keyword: "panchayat season review",       niche: "entertainment" },
  { keyword: "tvf india series review",       niche: "entertainment" },
  { keyword: "scam 1992 rewatch india",       niche: "entertainment" },
  { keyword: "aspirants india tvf",           niche: "entertainment" },
  { keyword: "kota factory india review",     niche: "entertainment" },
  { keyword: "bollywood actor ranking 2025",  niche: "entertainment" },
  { keyword: "ranveer singh movies",          niche: "entertainment" },
  { keyword: "deepika padukone 2025",         niche: "entertainment" },
  { keyword: "alia bhatt new movie",          niche: "entertainment" },
  { keyword: "shah rukh khan 2025",           niche: "entertainment" },
  { keyword: "salman khan film 2025",         niche: "entertainment" },
  { keyword: "south film industry india",     niche: "entertainment" },
  { keyword: "prabhas new movie",             niche: "entertainment" },
  { keyword: "allu arjun india",              niche: "entertainment" },
  { keyword: "tollywood india 2025",          niche: "entertainment" },
  { keyword: "kollywood india 2025",          niche: "entertainment" },
  { keyword: "mollywood india 2025",          niche: "entertainment" },
  { keyword: "ipl auction 2025",              niche: "entertainment" },
  { keyword: "ipl schedule 2025",             niche: "entertainment" },
  { keyword: "ms dhoni retirement",           niche: "entertainment" },
  { keyword: "t20 world cup india 2025",      niche: "entertainment" },
  { keyword: "bcci india cricket news",       niche: "entertainment" },
  { keyword: "kabaddi india pro league",      niche: "entertainment" },
  { keyword: "pro kho kho india",             niche: "entertainment" },
  { keyword: "indian football team",          niche: "entertainment" },
  { keyword: "bollywood music 2025 hits",     niche: "entertainment" },
  { keyword: "arijit singh new song",         niche: "entertainment" },
  { keyword: "ap dhillon india songs",        niche: "entertainment" },
  { keyword: "diljit dosanjh india tour",     niche: "entertainment" },
  { keyword: "badshah new song 2025",         niche: "entertainment" },
  { keyword: "divine rap india",              niche: "entertainment" },
  { keyword: "indian hip hop 2025",           niche: "entertainment" },
  { keyword: "indie music india",             niche: "entertainment" },
  { keyword: "comedy show india 2025",        niche: "entertainment" },
  { keyword: "zakir khan india standup",      niche: "entertainment" },
  { keyword: "kenny sebastian standup",       niche: "entertainment" },
  { keyword: "biswa kalyan rath india",       niche: "entertainment" },
  { keyword: "nfak music india",              niche: "entertainment" },
  { keyword: "lo fi music india study",       niche: "entertainment" },
  { keyword: "anime india community",         niche: "entertainment" },
  { keyword: "one piece india fans",          niche: "entertainment" },
  { keyword: "jujutsu kaisen india",          niche: "entertainment" },
  { keyword: "kpop india bts army",           niche: "entertainment" },
  { keyword: "blackpink india tour",          niche: "entertainment" },
  { keyword: "marvel india fans",             niche: "entertainment" },
  { keyword: "dc india fans",                 niche: "entertainment" },
  { keyword: "book reading india trend",      niche: "entertainment" },
  { keyword: "true crime india podcast",      niche: "entertainment" },
  { keyword: "finance podcast india",         niche: "entertainment" },
  { keyword: "history india podcast",         niche: "entertainment" },
  { keyword: "horror content india ott",      niche: "entertainment" },
  { keyword: "mythology india youtube",       niche: "entertainment" },

  // Creator (60)
  { keyword: "how to make reels fast india",  niche: "creator" },
  { keyword: "reel transition ideas india",   niche: "creator" },
  { keyword: "viral reel hook ideas",         niche: "creator" },
  { keyword: "instagram carousel ideas india",niche: "creator" },
  { keyword: "instagram story ideas india",   niche: "creator" },
  { keyword: "instagram bio ideas india",     niche: "creator" },
  { keyword: "instagram highlights india",    niche: "creator" },
  { keyword: "instagram growth 2025 india",   niche: "creator" },
  { keyword: "10k followers india fast",      niche: "creator" },
  { keyword: "100k followers india tips",     niche: "creator" },
  { keyword: "micro influencer india",        niche: "creator" },
  { keyword: "nano influencer india",         niche: "creator" },
  { keyword: "ugc creator india",             niche: "creator" },
  { keyword: "content calendar india",        niche: "creator" },
  { keyword: "content ideas india niche",     niche: "creator" },
  { keyword: "posting time india instagram",  niche: "creator" },
  { keyword: "reel length india tips",        niche: "creator" },
  { keyword: "youtube shorts growth india",   niche: "creator" },
  { keyword: "youtube channel start india",   niche: "creator" },
  { keyword: "youtube niche india 2025",      niche: "creator" },
  { keyword: "faceless youtube channel india",niche: "creator" },
  { keyword: "youtube thumbnail ctr india",   niche: "creator" },
  { keyword: "youtube seo india tips",        niche: "creator" },
  { keyword: "youtube description india",     niche: "creator" },
  { keyword: "youtube title formula india",   niche: "creator" },
  { keyword: "video editing app india",       niche: "creator" },
  { keyword: "capcut india tutorial",         niche: "creator" },
  { keyword: "inshot india tutorial",         niche: "creator" },
  { keyword: "premiere pro india",            niche: "creator" },
  { keyword: "da vinci resolve india",        niche: "creator" },
  { keyword: "camera india youtube budget",   niche: "creator" },
  { keyword: "ring light india setup",        niche: "creator" },
  { keyword: "microphone india youtube",      niche: "creator" },
  { keyword: "studio setup india budget",     niche: "creator" },
  { keyword: "green screen india tutorial",   niche: "creator" },
  { keyword: "teleprompter india setup",      niche: "creator" },
  { keyword: "podcast setup india budget",    niche: "creator" },
  { keyword: "podcast mic india review",      niche: "creator" },
  { keyword: "podcast india monetize",        niche: "creator" },
  { keyword: "spotify podcast india",         niche: "creator" },
  { keyword: "brand deal rate card india",    niche: "creator" },
  { keyword: "how to pitch brand india",      niche: "creator" },
  { keyword: "creator economy india 2025",    niche: "creator" },
  { keyword: "creator fund india",            niche: "creator" },
  { keyword: "meta creator program india",    niche: "creator" },
  { keyword: "youtube partner program india", niche: "creator" },
  { keyword: "sponsored content india",       niche: "creator" },
  { keyword: "whatsapp channel india",        niche: "creator" },
  { keyword: "telegram channel india tips",   niche: "creator" },
  { keyword: "community building india",      niche: "creator" },
  { keyword: "creator burnout india",         niche: "creator" },
  { keyword: "content block india fix",       niche: "creator" },
  { keyword: "ai tools creator india",        niche: "creator" },
  { keyword: "chatgpt content india",         niche: "creator" },
  { keyword: "script writing reels india",    niche: "creator" },
  { keyword: "voiceover india tips",          niche: "creator" },
  { keyword: "subtitles reels india",         niche: "creator" },
  { keyword: "analytics instagram india",     niche: "creator" },
  { keyword: "reach vs impressions india",    niche: "creator" },
  { keyword: "engagement rate india target",  niche: "creator" },
];

// ── TIER C — Breakout watchers + seasonal (200) ───────────────────────────────

const TIER_C_KEYWORDS: Omit<KeywordEntry, "tier">[] = [
  // Rising platform signals (30)
  { keyword: "threads india growth",          niche: "creator" },
  { keyword: "bluesky india",                 niche: "creator" },
  { keyword: "lemon8 india",                  niche: "creator" },
  { keyword: "moj india creators",            niche: "creator" },
  { keyword: "josh app india",                niche: "creator" },
  { keyword: "sharechat india creators",      niche: "creator" },
  { keyword: "koo app india",                 niche: "creator" },
  { keyword: "youtube podcasts india",        niche: "creator" },
  { keyword: "instagram notes india",         niche: "creator" },
  { keyword: "instagram add yours india",     niche: "creator" },
  { keyword: "instagram collabs india",       niche: "creator" },
  { keyword: "youtube community posts india", niche: "creator" },
  { keyword: "ai influencer india",           niche: "creator" },
  { keyword: "virtual creator india",         niche: "creator" },
  { keyword: "avatar creator india",          niche: "creator" },
  { keyword: "ar filter india creator",       niche: "creator" },
  { keyword: "live streaming india earn",     niche: "creator" },
  { keyword: "instagram live shopping india", niche: "creator" },
  { keyword: "youtube super chat india",      niche: "creator" },
  { keyword: "membership youtube india",      niche: "creator" },
  { keyword: "paid community india creator",  niche: "creator" },
  { keyword: "substack india writers",        niche: "creator" },
  { keyword: "newsletter india monetize",     niche: "creator" },
  { keyword: "gumroad india sell",            niche: "creator" },
  { keyword: "digital product india sell",    niche: "creator" },
  { keyword: "online course india sell",      niche: "creator" },
  { keyword: "cohort course india",           niche: "creator" },
  { keyword: "mentorship india creator",      niche: "creator" },
  { keyword: "patreon india",                 niche: "creator" },
  { keyword: "buymeacoffee india",            niche: "creator" },

  // Breakout tech topics (30)
  { keyword: "gpt 5 india",                   niche: "tech" },
  { keyword: "anthropic india",               niche: "tech" },
  { keyword: "openai india",                  niche: "tech" },
  { keyword: "sora video ai india",           niche: "tech" },
  { keyword: "veo 3 india",                   niche: "tech" },
  { keyword: "llm india tutorial",            niche: "tech" },
  { keyword: "local ai india run",            niche: "tech" },
  { keyword: "ollama india setup",            niche: "tech" },
  { keyword: "stable diffusion india",        niche: "tech" },
  { keyword: "ai automation india jobs",      niche: "tech" },
  { keyword: "agentic ai india",              niche: "tech" },
  { keyword: "no code india tools",           niche: "tech" },
  { keyword: "low code india platform",       niche: "tech" },
  { keyword: "tata ai india",                 niche: "tech" },
  { keyword: "reliance jio ai india",         niche: "tech" },
  { keyword: "indic ai model india",          niche: "tech" },
  { keyword: "bhashini india",                niche: "tech" },
  { keyword: "govt digital india 2025",       niche: "tech" },
  { keyword: "upi new features india",        niche: "tech" },
  { keyword: "india fintech 2025",            niche: "tech" },
  { keyword: "india semiconductor chip",      niche: "tech" },
  { keyword: "india space tech isro",         niche: "tech" },
  { keyword: "india defence tech 2025",       niche: "tech" },
  { keyword: "india drone delivery",          niche: "tech" },
  { keyword: "hyperloop india",               niche: "tech" },
  { keyword: "quantum computing india",       niche: "tech" },
  { keyword: "robotics india jobs",           niche: "tech" },
  { keyword: "biotech india 2025",            niche: "tech" },
  { keyword: "edtech india 2025",             niche: "tech" },
  { keyword: "healthtech india 2025",         niche: "tech" },

  // Seasonal / Festival (40)
  { keyword: "diwali 2025 ideas",             niche: "lifestyle" },
  { keyword: "navratri 2025 outfit",          niche: "fashion" },
  { keyword: "durga puja 2025",               niche: "entertainment" },
  { keyword: "eid 2025 india",                niche: "lifestyle" },
  { keyword: "holi 2025 celebration",         niche: "lifestyle" },
  { keyword: "christmas india 2025",          niche: "lifestyle" },
  { keyword: "new year india 2026",           niche: "lifestyle" },
  { keyword: "valentine's day india 2025",    niche: "lifestyle" },
  { keyword: "republic day india 2025",       niche: "lifestyle" },
  { keyword: "independence day india 2025",   niche: "lifestyle" },
  { keyword: "teacher's day india 2025",      niche: "education" },
  { keyword: "world mental health day india", niche: "fitness" },
  { keyword: "world yoga day india",          niche: "fitness" },
  { keyword: "women's day india 2025",        niche: "lifestyle" },
  { keyword: "mother's day india 2025",       niche: "lifestyle" },
  { keyword: "father's day india 2025",       niche: "lifestyle" },
  { keyword: "friendship day india 2025",     niche: "lifestyle" },
  { keyword: "children's day india",          niche: "lifestyle" },
  { keyword: "ganesh chaturthi 2025",         niche: "entertainment" },
  { keyword: "pongal 2025 india",             niche: "food" },
  { keyword: "baisakhi 2025 india",           niche: "entertainment" },
  { keyword: "onam 2025 india",               niche: "food" },
  { keyword: "ugadi 2025 india",              niche: "lifestyle" },
  { keyword: "karwa chauth india 2025",       niche: "lifestyle" },
  { keyword: "raksha bandhan 2025",           niche: "lifestyle" },
  { keyword: "janmashtami 2025 india",        niche: "entertainment" },
  { keyword: "makar sankranti 2025",          niche: "lifestyle" },
  { keyword: "lohri 2025 india",              niche: "lifestyle" },
  { keyword: "chhath puja 2025",              niche: "entertainment" },
  { keyword: "muharram india 2025",           niche: "entertainment" },
  { keyword: "black friday india 2025",       niche: "fashion" },
  { keyword: "great indian festival 2025",    niche: "finance" },
  { keyword: "big billion days 2025",         niche: "finance" },
  { keyword: "end of season sale india",      niche: "fashion" },
  { keyword: "summer sale india 2025",        niche: "fashion" },
  { keyword: "winter sale india 2025",        niche: "fashion" },
  { keyword: "back to school india 2025",     niche: "education" },
  { keyword: "exam season india tips",        niche: "education" },
  { keyword: "board exam india 2025",         niche: "education" },
  { keyword: "result day india 2025",         niche: "education" },

  // Macro & current affairs India (30)
  { keyword: "india economy 2025",            niche: "finance" },
  { keyword: "india gdp 2025",               niche: "finance" },
  { keyword: "india budget 2025 impact",      niche: "finance" },
  { keyword: "india election news",           niche: "entertainment" },
  { keyword: "modi government 2025",          niche: "entertainment" },
  { keyword: "india china relations 2025",    niche: "entertainment" },
  { keyword: "india us relations 2025",       niche: "entertainment" },
  { keyword: "india pakistan news 2025",      niche: "entertainment" },
  { keyword: "india jobs market 2025",        niche: "education" },
  { keyword: "india recession 2025",          niche: "finance" },
  { keyword: "india inflation 2025",          niche: "finance" },
  { keyword: "india environment 2025",        niche: "lifestyle" },
  { keyword: "heat wave india 2025",          niche: "lifestyle" },
  { keyword: "india monsoon 2025",            niche: "lifestyle" },
  { keyword: "india flood 2025",              niche: "lifestyle" },
  { keyword: "india infrastructure 2025",     niche: "lifestyle" },
  { keyword: "india metro cities 2025",       niche: "lifestyle" },
  { keyword: "india cost of living 2025",     niche: "finance" },
  { keyword: "india housing market 2025",     niche: "finance" },
  { keyword: "india youth unemployment",      niche: "education" },
  { keyword: "india skilled labour 2025",     niche: "education" },
  { keyword: "india population data 2025",    niche: "lifestyle" },
  { keyword: "india new policy 2025",         niche: "finance" },
  { keyword: "india supreme court news",      niche: "entertainment" },
  { keyword: "india social media law",        niche: "creator" },
  { keyword: "creator regulation india",      niche: "creator" },
  { keyword: "it act india creators",         niche: "creator" },
  { keyword: "india ai regulation",           niche: "tech" },
  { keyword: "india data privacy law",        niche: "tech" },
  { keyword: "dpdp act india impact",         niche: "tech" },

  // Breakout finance / market signals (30)
  { keyword: "smallcap rally india 2025",     niche: "finance" },
  { keyword: "midcap stocks india 2025",      niche: "finance" },
  { keyword: "nifty new high 2025",           niche: "finance" },
  { keyword: "fii dii india data",            niche: "finance" },
  { keyword: "india rate cut rbi",            niche: "finance" },
  { keyword: "india bond yield 2025",         niche: "finance" },
  { keyword: "india rupee dollar 2025",       niche: "finance" },
  { keyword: "us tariff india impact",        niche: "finance" },
  { keyword: "china india trade 2025",        niche: "finance" },
  { keyword: "india export 2025",             niche: "finance" },
  { keyword: "india import 2025",             niche: "finance" },
  { keyword: "oil price india impact",        niche: "finance" },
  { keyword: "petrol price india 2025",       niche: "finance" },
  { keyword: "electricity bill india 2025",   niche: "finance" },
  { keyword: "emi increase india 2025",       niche: "finance" },
  { keyword: "ipo listing india 2025",        niche: "finance" },
  { keyword: "startup layoff india 2025",     niche: "education" },
  { keyword: "startup funding india 2025",    niche: "education" },
  { keyword: "unicorn india 2025",            niche: "education" },
  { keyword: "india m&a 2025",               niche: "finance" },
  { keyword: "tata group 2025 news",          niche: "finance" },
  { keyword: "reliance jio news 2025",        niche: "finance" },
  { keyword: "adani group 2025",              niche: "finance" },
  { keyword: "infosys results 2025",          niche: "finance" },
  { keyword: "tcs results india 2025",        niche: "finance" },
  { keyword: "hdfc results 2025",             niche: "finance" },
  { keyword: "sbi results 2025",              niche: "finance" },
  { keyword: "bajaj finance india",           niche: "finance" },
  { keyword: "zomato stock india",            niche: "finance" },
  { keyword: "nykaa stock india 2025",        niche: "finance" },

  // Viral / meme driven (40)
  { keyword: "trending meme india 2025",      niche: "entertainment" },
  { keyword: "viral video india 2025",        niche: "entertainment" },
  { keyword: "india challenge instagram",     niche: "creator" },
  { keyword: "trending dance india 2025",     niche: "entertainment" },
  { keyword: "trending song india 2025",      niche: "entertainment" },
  { keyword: "viral audio india reels",       niche: "creator" },
  { keyword: "new trend india youtube",       niche: "creator" },
  { keyword: "india controversy youtube",     niche: "entertainment" },
  { keyword: "roast video india",             niche: "entertainment" },
  { keyword: "reaction video india",          niche: "entertainment" },
  { keyword: "collab india creators",         niche: "creator" },
  { keyword: "india podcast clip viral",      niche: "creator" },
  { keyword: "bhuvan bam new video",          niche: "entertainment" },
  { keyword: "ashish chanchlani new",         niche: "entertainment" },
  { keyword: "triggered insaan india",        niche: "entertainment" },
  { keyword: "technical guruji india",        niche: "tech" },
  { keyword: "dhruv rathee new video",        niche: "entertainment" },
  { keyword: "ranveer allahbadia podcast",    niche: "education" },
  { keyword: "nikhil kamath india",           niche: "finance" },
  { keyword: "pranjal kamra india",           niche: "finance" },
  { keyword: "warikoo india advice",          niche: "education" },
  { keyword: "ankur warikoo new video",       niche: "education" },
  { keyword: "rachana ranade india",          niche: "finance" },
  { keyword: "sharan hegde india",            niche: "finance" },
  { keyword: "akshat shrivastava india",      niche: "finance" },
  { keyword: "sourav ganguly india news",     niche: "entertainment" },
  { keyword: "sonu nigam india news",         niche: "entertainment" },
  { keyword: "kapil sharma show",             niche: "entertainment" },
  { keyword: "shark tank india 2025",         niche: "education" },
  { keyword: "kbc india 2025",                niche: "entertainment" },
  { keyword: "india got talent 2025",         niche: "entertainment" },
  { keyword: "masterchef india 2025",         niche: "food" },
  { keyword: "roadies india 2025",            niche: "entertainment" },
  { keyword: "mtv splitsvilla 2025",          niche: "entertainment" },
  { keyword: "dating show india ott",         niche: "entertainment" },
  { keyword: "comedy nights india",           niche: "entertainment" },
  { keyword: "india travel viral spot",       niche: "lifestyle" },
  { keyword: "hidden gems india travel",      niche: "lifestyle" },
  { keyword: "india food challenge",          niche: "food" },
  { keyword: "india spicy food challenge",    niche: "food" },
];

// ── Assemble and export ───────────────────────────────────────────────────────

export const ALL_KEYWORDS: KeywordEntry[] = [
  ...TIER_A_KEYWORDS.map(k => ({ ...k, tier: "A" as TrendTier })),
  ...TIER_B_KEYWORDS.map(k => ({ ...k, tier: "B" as TrendTier })),
  ...TIER_C_KEYWORDS.map(k => ({ ...k, tier: "C" as TrendTier })),
];

export const KEYWORDS_BY_TIER = {
  A: ALL_KEYWORDS.filter(k => k.tier === "A"),
  B: ALL_KEYWORDS.filter(k => k.tier === "B"),
  C: ALL_KEYWORDS.filter(k => k.tier === "C"),
};

export function getKeywordsByTier(tier: TrendTier): KeywordEntry[] {
  return KEYWORDS_BY_TIER[tier];
}

export function getKeywordsByNiche(niche: string): KeywordEntry[] {
  return ALL_KEYWORDS.filter(k => k.niche === niche);
}

// Sanity check at module load
const total = ALL_KEYWORDS.length;
if (total < 900) {
  console.warn(`[keywords] WARNING: only ${total} keywords loaded (expected ~1000)`);
}